[package]
name = "log4rs_ldp"
version = "0.1.0"
authors = ["Cédric Dumay <cedric.dumay@ovh.net>"]

[dependencies]
log = "0.4"
log4rs = "0.8"
log4rs_gelf = { git = "https://github.com/cdumay/log4rs-gelf" }
serde_json = "1.0"
